version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  # The build job
  build:
    working_directory: ~/project
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
